services:
 

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.test-project-backend.rule=Host(`test-project.gkibria121.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.test-project-backend.entrypoints=web"
      - "traefik.http.services.test-project-backend.loadbalancer.server.port=8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=test-project;Username=root;Password=toor
 
    networks:
      - traefik-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=https://test-project.gkibria121.com/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-project-frontend.rule=Host(`test-project.gkibria121.com`)"
      - "traefik.http.routers.test-project-frontend.entrypoints=web"
      - "traefik.http.services.test-project-frontend.loadbalancer.server.port=80"
    networks:
      - traefik-network
    environment:
      - VITE_BACKEND_URL=https://test-project.gkibria121.com/api

  
networks:
  traefik-network:
    external: true
